import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { ThreatCloudDB } from '../src/database.js';
import { QueryHandlers } from '../src/query-handlers.js';
import { CorrelationEngine } from '../src/correlation-engine.js';
import { join } from 'node:path';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';

describe('QueryHandlers', () => {
  let dbWrapper: ThreatCloudDB;
  let handlers: QueryHandlers;
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'query-test-'));
    dbWrapper = new ThreatCloudDB(join(tempDir, 'test.db'));
    const db = dbWrapper.getDB();
    handlers = new QueryHandlers(db);
    // Ensure campaigns + generated_patterns tables exist (created by CorrelationEngine)
    new CorrelationEngine(db);
  });

  afterEach(() => {
    dbWrapper.close();
    try {
      rmSync(tempDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });

  function insertEvents(count: number, overrides: Partial<{
    ip: string; attackType: string; technique: string; region: string; severity: string;
  }> = {}) {
    const baseTime = new Date();
    for (let i = 0; i < count; i++) {
      dbWrapper.insertEnrichedThreat(
        ThreatCloudDB.guardToEnriched({
          attackSourceIP: overrides.ip ?? `10.0.0.${i + 1}`,
          attackType: overrides.attackType ?? 'brute_force',
          mitreTechnique: overrides.technique ?? 'T1110',
          sigmaRuleMatched: `r-${i}-${Math.random().toString(36).slice(2, 8)}`,
          timestamp: new Date(baseTime.getTime() - i * 60_000).toISOString(),
          region: overrides.region ?? 'TW',
        })
      );
    }
  }

  // -------------------------------------------------------------------------
  // Time Series
  // -------------------------------------------------------------------------

  it('should return time series data grouped by day', () => {
    insertEvents(5);
    const result = handlers.getTimeSeries('day');
    expect(result.length).toBeGreaterThan(0);
    expect(result[0]).toHaveProperty('timestamp');
    expect(result[0]).toHaveProperty('count');
  });

  it('should return empty array for no data', () => {
    const result = handlers.getTimeSeries('day');
    expect(result).toEqual([]);
  });

  it('should filter by attack type', () => {
    insertEvents(3, { attackType: 'brute_force', ip: '10.5.0.1' });
    insertEvents(2, { attackType: 'scan', ip: '10.6.0.1' });

    const result = handlers.getTimeSeries('day', undefined, 'scan');
    const totalCount = result.reduce((sum, r) => sum + r.count, 0);
    expect(totalCount).toBe(2);
  });

  // -------------------------------------------------------------------------
  // Geo Distribution
  // -------------------------------------------------------------------------

  it('should return geo distribution', () => {
    insertEvents(3, { region: 'TW', ip: '10.1.0.1' });
    insertEvents(2, { region: 'JP', ip: '10.2.0.1' });

    const result = handlers.getGeoDistribution();
    expect(result.length).toBe(2);

    const tw = result.find((r) => r.region === 'TW');
    expect(tw).toBeDefined();
    expect(tw!.count).toBe(3);
    expect(tw!.uniqueIPs).toBeGreaterThan(0);
    expect(tw!.topAttackTypes.length).toBeGreaterThan(0);
  });

  // -------------------------------------------------------------------------
  // Trends
  // -------------------------------------------------------------------------

  it('should return trends', () => {
    insertEvents(3, { attackType: 'brute_force' });
    const result = handlers.getTrends(7);
    expect(result.length).toBeGreaterThan(0);
    expect(result[0]).toHaveProperty('attackType');
    expect(result[0]).toHaveProperty('direction');
  });

  // -------------------------------------------------------------------------
  // MITRE Heatmap
  // -------------------------------------------------------------------------

  it('should return MITRE heatmap', () => {
    insertEvents(3, { technique: 'T1110', ip: '10.3.0.1' });
    insertEvents(2, { technique: 'T1046', ip: '10.4.0.1' });

    const result = handlers.getMitreHeatmap();
    expect(result.length).toBe(2);
    expect(result[0].technique).toBe('T1110');
    expect(result[0].count).toBe(3);
  });

  // -------------------------------------------------------------------------
  // Enhanced Stats
  // -------------------------------------------------------------------------

  it('should return enhanced stats', () => {
    insertEvents(3);
    const stats = handlers.getEnhancedStats();
    expect(stats).toHaveProperty('totalThreats');
    expect(stats).toHaveProperty('totalIoCs');
    expect(stats).toHaveProperty('activeCampaigns');
    expect(stats).toHaveProperty('autoGeneratedRules');
    expect(stats).toHaveProperty('trapEventsCount');
    expect(stats).toHaveProperty('guardEventsCount');
    expect(stats).toHaveProperty('topRegions');
  });
});
