/**
 * Real-time rule statistics by scanning the filesystem.
 * Counts Sigma (.yml) and YARA (.yar) rules across community, custom,
 * and auto-generated directories.
 *
 * @module @panguard-ai/threat-cloud/api/stats
 */

import { readdirSync, readFileSync, existsSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';

/** Counts per rule source (community / custom / auto-generated). */
export interface RuleSourceCounts {
  readonly community: number;
  readonly custom: number;
  readonly autoGenerated: number;
  readonly total: number;
}

/** YARA-specific counts that include rule definitions inside files. */
export interface YaraRuleCounts extends RuleSourceCounts {
  readonly definitions: number;
}

/** Auto-generated rule metadata. */
export interface AutoGeneratedMeta {
  readonly sigma: number;
  readonly yara: number;
  readonly promoted: number;
  readonly draft: number;
}

/** Full rule statistics response. */
export interface RuleStats {
  readonly sigma: RuleSourceCounts;
  readonly yara: YaraRuleCounts;
  readonly totalRules: number;
  readonly autoGenerated: AutoGeneratedMeta;
  readonly lastSync: string | null;
  readonly sources: number;
  readonly validatedRecords: number;
}

/**
 * Recursively count files matching an extension inside a directory.
 */
function countFiles(dir: string, ext: string): number {
  if (!existsSync(dir)) {
    return 0;
  }
  try {
    let count = 0;
    const entries = readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        count += countFiles(join(dir, entry.name), ext);
      } else if (entry.name.endsWith(ext) && !entry.name.startsWith('.')) {
        count += 1;
      }
    }
    return count;
  } catch {
    return 0;
  }
}

/**
 * Count YARA rule definitions (lines starting with "rule ") inside .yar files.
 */
function countYaraDefinitions(dir: string): number {
  if (!existsSync(dir)) {
    return 0;
  }
  try {
    let count = 0;
    const entries = readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        count += countYaraDefinitions(fullPath);
      } else if (entry.name.endsWith('.yar') && !entry.name.startsWith('.')) {
        try {
          const content = readFileSync(fullPath, 'utf-8');
          const lines = content.split('\n');
          for (const line of lines) {
            if (/^rule\s+/.test(line.trimStart())) {
              count += 1;
            }
          }
        } catch {
          // skip unreadable files
        }
      }
    }
    return count;
  } catch {
    return 0;
  }
}

/**
 * Read a JSON file and parse it, returning null on failure.
 */
function readJsonSafe<T>(filePath: string): T | null {
  try {
    if (!existsSync(filePath)) {
      return null;
    }
    const raw = readFileSync(filePath, 'utf-8');
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

interface SyncState {
  lastSyncAt?: string;
  totalRecordsAllTime?: number;
}

interface SyncStats {
  totalRecords?: number;
  perSource?: ReadonlyArray<{ source: string; validated: number }>;
}

interface RulesMeta {
  sigmaRules?: number;
  yaraRules?: number;
  sigmaByStatus?: Record<string, number>;
  yaraByStatus?: Record<string, number>;
}

/**
 * Scan the filesystem for real-time rule counts.
 *
 * All paths are resolved relative to `process.cwd()` (expected to be the
 * monorepo root).
 */
export function getRuleStats(): RuleStats {
  const root = process.cwd();

  // -- Sigma directories --
  const sigmaBase = resolve(root, 'config/sigma-rules');
  const sigmaCommunity = countFiles(join(sigmaBase, 'community'), '.yml');
  const sigmaCustom = countFiles(join(sigmaBase, 'custom'), '.yml');
  const sigmaAutoGen = countFiles(join(sigmaBase, 'auto-generated'), '.yml');
  const sigmaTotal = sigmaCommunity + sigmaCustom + sigmaAutoGen;

  // -- YARA directories --
  const yaraBase = resolve(root, 'config/yara-rules');
  const yaraCommunity = countFiles(join(yaraBase, 'community'), '.yar');
  const yaraCustom = countFiles(join(yaraBase, 'custom'), '.yar');
  const yaraAutoGen = countFiles(join(yaraBase, 'auto-generated'), '.yar');
  const yaraTotal = yaraCommunity + yaraCustom + yaraAutoGen;

  // Count actual rule definitions inside YARA files
  const yaraDefinitions =
    countYaraDefinitions(join(yaraBase, 'community')) +
    countYaraDefinitions(join(yaraBase, 'custom')) +
    countYaraDefinitions(join(yaraBase, 'auto-generated'));

  // -- Sync state --
  const syncStatePath = resolve(
    root,
    'packages/threat-cloud/data/threat-intel/sync-state.json',
  );
  const syncState = readJsonSafe<SyncState>(syncStatePath);

  // -- Sync stats (for sources + validated records) --
  const syncStatsPath = resolve(
    root,
    'packages/threat-cloud/data/threat-intel/sync-stats.json',
  );
  const syncStats = readJsonSafe<SyncStats>(syncStatsPath);

  const sources = syncStats?.perSource
    ? syncStats.perSource.filter((s) => s.validated > 0).length
    : 0;
  const validatedRecords = syncStats?.totalRecords ?? 0;

  // -- Auto-generated meta --
  const metaPath = resolve(
    sigmaBase,
    'auto-generated/.rules-meta.json',
  );
  const meta = readJsonSafe<RulesMeta>(metaPath);

  const draftSigma = meta?.sigmaByStatus?.['draft'] ?? 0;
  const draftYara = meta?.yaraByStatus?.['draft'] ?? 0;
  const promotedSigma = meta?.sigmaByStatus?.['promoted'] ?? 0;
  const promotedYara = meta?.yaraByStatus?.['promoted'] ?? 0;

  return {
    sigma: {
      community: sigmaCommunity,
      custom: sigmaCustom,
      autoGenerated: sigmaAutoGen,
      total: sigmaTotal,
    },
    yara: {
      community: yaraCommunity,
      custom: yaraCustom,
      autoGenerated: yaraAutoGen,
      total: yaraTotal,
      definitions: yaraDefinitions,
    },
    totalRules: sigmaTotal + yaraTotal,
    autoGenerated: {
      sigma: meta?.sigmaRules ?? sigmaAutoGen,
      yara: meta?.yaraRules ?? yaraAutoGen,
      promoted: promotedSigma + promotedYara,
      draft: draftSigma + draftYara,
    },
    lastSync: syncState?.lastSyncAt ?? null,
    sources,
    validatedRecords,
  };
}
