/**
 * Report Templates (zh-TW / en)
 * 報告範本（繁體中文 / 英文）
 *
 * Provides bilingual template strings and layouts for compliance reports.
 * 提供雙語範本字串和合規報告版面配置。
 *
 * @module @panguard-ai/panguard-report/templates
 */

import type { ComplianceFramework, ReportLanguage } from '../types.js';

// ---------------------------------------------------------------------------
// Report section labels
// 報告區段標籤
// ---------------------------------------------------------------------------

/** Section labels by language / 各語言的區段標籤 */
export interface ReportSectionLabels {
  title: string;
  executiveSummary: string;
  complianceOverview: string;
  controlDetails: string;
  findings: string;
  recommendations: string;
  statistics: string;
  appendix: string;
  generatedBy: string;
  reportPeriod: string;
  organization: string;
  reportId: string;
  overallScore: string;
  controlsPassed: string;
  controlsFailed: string;
  controlsPartial: string;
  controlsNA: string;
  severity: string;
  priority: string;
  estimatedEffort: string;
  category: string;
  status: string;
  evidence: string;
  remediation: string;
}

const LABELS_EN: ReportSectionLabels = {
  title: 'Compliance Report',
  executiveSummary: 'Executive Summary',
  complianceOverview: 'Compliance Overview',
  controlDetails: 'Control Details',
  findings: 'Findings',
  recommendations: 'Recommendations',
  statistics: 'Statistics',
  appendix: 'Appendix',
  generatedBy: 'Generated by Panguard AI / Panguard AI',
  reportPeriod: 'Report Period',
  organization: 'Organization',
  reportId: 'Report ID',
  overallScore: 'Overall Compliance Score',
  controlsPassed: 'Passed',
  controlsFailed: 'Failed',
  controlsPartial: 'Partial',
  controlsNA: 'Not Applicable',
  severity: 'Severity',
  priority: 'Priority',
  estimatedEffort: 'Estimated Effort',
  category: 'Category',
  status: 'Status',
  evidence: 'Evidence',
  remediation: 'Remediation',
};

const LABELS_ZH: ReportSectionLabels = {
  title: '合規報告',
  executiveSummary: '執行摘要',
  complianceOverview: '合規概覽',
  controlDetails: '控制項詳情',
  findings: '發現',
  recommendations: '建議',
  statistics: '統計',
  appendix: '附錄',
  generatedBy: '由 Panguard AI / Panguard AI 產生',
  reportPeriod: '報告期間',
  organization: '組織',
  reportId: '報告 ID',
  overallScore: '整體合規分數',
  controlsPassed: '通過',
  controlsFailed: '未通過',
  controlsPartial: '部分符合',
  controlsNA: '不適用',
  severity: '嚴重度',
  priority: '優先級',
  estimatedEffort: '預估工作量',
  category: '分類',
  status: '狀態',
  evidence: '證據',
  remediation: '修復建議',
};

/**
 * Get section labels for a given language
 * 取得指定語言的區段標籤
 */
export function getSectionLabels(language: ReportLanguage): ReportSectionLabels {
  return language === 'zh-TW' ? LABELS_ZH : LABELS_EN;
}

// ---------------------------------------------------------------------------
// Status labels
// 狀態標籤
// ---------------------------------------------------------------------------

const STATUS_LABELS_EN: Record<string, string> = {
  pass: 'Pass',
  fail: 'Fail',
  partial: 'Partial',
  not_applicable: 'N/A',
};

const STATUS_LABELS_ZH: Record<string, string> = {
  pass: '通過',
  fail: '未通過',
  partial: '部分符合',
  not_applicable: '不適用',
};

/**
 * Get status label for display
 * 取得狀態標籤供顯示
 */
export function getStatusLabel(status: string, language: ReportLanguage): string {
  const labels = language === 'zh-TW' ? STATUS_LABELS_ZH : STATUS_LABELS_EN;
  return labels[status] ?? status;
}

// ---------------------------------------------------------------------------
// Severity labels
// 嚴重度標籤
// ---------------------------------------------------------------------------

const SEVERITY_LABELS_EN: Record<string, string> = {
  critical: 'Critical',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
  info: 'Info',
};

const SEVERITY_LABELS_ZH: Record<string, string> = {
  critical: '嚴重',
  high: '高',
  medium: '中',
  low: '低',
  info: '資訊',
};

/**
 * Get severity label for display
 * 取得嚴重度標籤供顯示
 */
export function getSeverityLabel(severity: string, language: ReportLanguage): string {
  const labels = language === 'zh-TW' ? SEVERITY_LABELS_ZH : SEVERITY_LABELS_EN;
  return labels[severity] ?? severity;
}

// ---------------------------------------------------------------------------
// Priority labels
// 優先級標籤
// ---------------------------------------------------------------------------

const PRIORITY_LABELS_EN: Record<string, string> = {
  immediate: 'Immediate',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
};

const PRIORITY_LABELS_ZH: Record<string, string> = {
  immediate: '立即',
  high: '高',
  medium: '中',
  low: '低',
};

/**
 * Get priority label for display
 * 取得優先級標籤供顯示
 */
export function getPriorityLabel(priority: string, language: ReportLanguage): string {
  const labels = language === 'zh-TW' ? PRIORITY_LABELS_ZH : PRIORITY_LABELS_EN;
  return labels[priority] ?? priority;
}

// ---------------------------------------------------------------------------
// Framework descriptions for report covers
// 框架描述（供報告封面使用）
// ---------------------------------------------------------------------------

/** Framework description template / 框架描述範本 */
export interface FrameworkDescription {
  fullName: string;
  shortDescription: string;
  scope: string;
}

const FRAMEWORK_DESCRIPTIONS: Record<ComplianceFramework, Record<ReportLanguage, FrameworkDescription>> = {
  tw_cyber_security_act: {
    en: {
      fullName: 'Taiwan Cyber Security Management Act',
      shortDescription: 'Compliance assessment based on the Cyber Security Management Act and its enforcement rules.',
      scope: 'Government agencies, critical infrastructure operators, and designated enterprises.',
    },
    'zh-TW': {
      fullName: '資通安全管理法',
      shortDescription: '基於資通安全管理法及其施行細則的合規評估。',
      scope: '政府機關、關鍵基礎設施營運者及特定企業。',
    },
  },
  iso27001: {
    en: {
      fullName: 'ISO/IEC 27001:2022 Information Security Management',
      shortDescription: 'Assessment based on ISO/IEC 27001:2022 Annex A controls.',
      scope: 'Organizations implementing an Information Security Management System (ISMS).',
    },
    'zh-TW': {
      fullName: 'ISO/IEC 27001:2022 資訊安全管理',
      shortDescription: '基於 ISO/IEC 27001:2022 附錄 A 控制項的評估。',
      scope: '實施資訊安全管理系統 (ISMS) 的組織。',
    },
  },
  soc2: {
    en: {
      fullName: 'SOC 2 Trust Services Criteria',
      shortDescription: 'Assessment based on AICPA SOC 2 Type II Trust Services Criteria.',
      scope: 'Service organizations that handle customer data.',
    },
    'zh-TW': {
      fullName: 'SOC 2 信任服務準則',
      shortDescription: '基於 AICPA SOC 2 Type II 信任服務準則的評估。',
      scope: '處理客戶資料的服務組織。',
    },
  },
};

/**
 * Get framework description for reports
 * 取得框架描述供報告使用
 */
export function getFrameworkDescription(
  framework: ComplianceFramework,
  language: ReportLanguage,
): FrameworkDescription {
  return FRAMEWORK_DESCRIPTIONS[framework][language];
}
