#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MANIFEST="$SCRIPT_DIR/manifest.json"
FIGMA_URL="https://www.figma.com/design/cs19iL8Jh0JIAq1LcXXdCg"

echo ""
echo "================================================"
echo "  Panguard AI - Dashboard Plugin Installer"
echo "================================================"
echo ""
echo "$MANIFEST" | pbcopy
echo "[OK] Manifest path copied to clipboard:"
echo "     $MANIFEST"
echo ""
echo "[OK] Opening Figma..."
open "$FIGMA_URL"
echo ""
echo "  1. Menu > Plugins > Development"
echo "     > Import plugin from manifest..."
echo "  2. Cmd+V, select manifest.json"
echo "  3. Menu > Plugins > Development"
echo "     > Panguard AI Dashboard"
echo ""
echo "================================================"
echo ""
