'use client';

import { useState, useEffect } from 'react';
import { STATS } from '@/lib/stats';

export interface ThreatIntelStats {
  sigmaRules: number;
  yaraRules: number;
  validatedRecords: number;
  sources: number;
  autoGeneratedSigma: number;
  autoGeneratedYara: number;
  promotedRules: number;
  draftRules: number;
  lastSync: string;
  syncInterval: string;
}

const CACHE_KEY = 'panguard-tc-stats';
const CACHE_TTL = 5 * 60 * 1000; // 5 minutes (live page, shorter TTL)

interface CachedData {
  data: ThreatIntelStats;
  timestamp: number;
}

const FALLBACK: ThreatIntelStats = {
  sigmaRules: STATS.sigmaRules,
  yaraRules: STATS.yaraRules,
  validatedRecords: STATS.threatIntel.validatedRecords,
  sources: STATS.threatIntel.sources,
  autoGeneratedSigma: STATS.threatIntel.autoGeneratedSigma,
  autoGeneratedYara: STATS.threatIntel.autoGeneratedYara,
  promotedRules: STATS.threatIntel.promotedRules,
  draftRules: STATS.threatIntel.draftRules,
  lastSync: STATS.threatIntel.lastSync,
  syncInterval: STATS.threatIntel.syncInterval,
};

function getFromCache(): ThreatIntelStats | null {
  try {
    const raw = sessionStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    const cached = JSON.parse(raw) as CachedData;
    if (Date.now() - cached.timestamp > CACHE_TTL) {
      sessionStorage.removeItem(CACHE_KEY);
      return null;
    }
    return cached.data;
  } catch {
    return null;
  }
}

function setCache(data: ThreatIntelStats): void {
  try {
    sessionStorage.setItem(CACHE_KEY, JSON.stringify({ data, timestamp: Date.now() }));
  } catch {
    // sessionStorage full or unavailable
  }
}

/**
 * Fetches live threat intel stats from /api/threat-intel/stats.
 * Falls back to static STATS values during SSR or on error.
 * Client-side cache TTL: 5 minutes.
 */
export function useThreatIntelStats(): ThreatIntelStats {
  const [stats, setStats] = useState<ThreatIntelStats>(FALLBACK);

  useEffect(() => {
    const cached = getFromCache();
    if (cached) {
      setStats(cached);
      return;
    }

    let cancelled = false;

    fetch('/api/threat-intel/stats')
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        if (cancelled) return;
        const live: ThreatIntelStats = {
          sigmaRules: data.sigma?.total ?? FALLBACK.sigmaRules,
          yaraRules: data.yara?.definitions ?? data.yara?.total ?? FALLBACK.yaraRules,
          validatedRecords: data.validatedRecords ?? FALLBACK.validatedRecords,
          sources: data.sources ?? FALLBACK.sources,
          autoGeneratedSigma: data.autoGenerated?.sigma ?? FALLBACK.autoGeneratedSigma,
          autoGeneratedYara: data.autoGenerated?.yara ?? FALLBACK.autoGeneratedYara,
          promotedRules: data.autoGenerated?.promoted ?? FALLBACK.promotedRules,
          draftRules: data.autoGenerated?.draft ?? FALLBACK.draftRules,
          lastSync: data.lastSync ?? FALLBACK.lastSync,
          syncInterval: FALLBACK.syncInterval, // always '1h', not from API
        };
        setStats(live);
        setCache(live);
      })
      .catch(() => {
        // Keep fallback values on error
      });

    return () => {
      cancelled = true;
    };
  }, []);

  return stats;
}
