import { NextResponse } from 'next/server';
import { readdirSync, readFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

/**
 * GET /api/threat-intel/stats
 *
 * Returns real-time rule counts by scanning the filesystem.
 * Paths are resolved relative to process.cwd() (monorepo root).
 */

function countFiles(dir: string, ext: string): number {
  if (!existsSync(dir)) return 0;
  try {
    let count = 0;
    const entries = readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        count += countFiles(join(dir, entry.name), ext);
      } else if (entry.name.endsWith(ext) && !entry.name.startsWith('.')) {
        count += 1;
      }
    }
    return count;
  } catch {
    return 0;
  }
}

function countYaraDefinitions(dir: string): number {
  if (!existsSync(dir)) return 0;
  try {
    let count = 0;
    const entries = readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        count += countYaraDefinitions(fullPath);
      } else if (entry.name.endsWith('.yar') && !entry.name.startsWith('.')) {
        try {
          const content = readFileSync(fullPath, 'utf-8');
          for (const line of content.split('\n')) {
            if (/^rule\s+/.test(line.trimStart())) {
              count += 1;
            }
          }
        } catch {
          // skip unreadable files
        }
      }
    }
    return count;
  } catch {
    return 0;
  }
}

function readJsonSafe<T>(filePath: string): T | null {
  try {
    if (!existsSync(filePath)) return null;
    return JSON.parse(readFileSync(filePath, 'utf-8')) as T;
  } catch {
    return null;
  }
}

interface SyncState {
  lastSyncAt?: string;
}

interface SyncStats {
  totalRecords?: number;
  perSource?: ReadonlyArray<{ source: string; validated: number }>;
}

interface RulesMeta {
  sigmaRules?: number;
  yaraRules?: number;
  sigmaByStatus?: Record<string, number>;
  yaraByStatus?: Record<string, number>;
}

export async function GET() {
  try {
    const root = process.cwd();

    const sigmaBase = resolve(root, 'config/sigma-rules');
    const sigmaCommunity = countFiles(join(sigmaBase, 'community'), '.yml');
    const sigmaCustom = countFiles(join(sigmaBase, 'custom'), '.yml');
    const sigmaAutoGen = countFiles(join(sigmaBase, 'auto-generated'), '.yml');
    const sigmaTotal = sigmaCommunity + sigmaCustom + sigmaAutoGen;

    const yaraBase = resolve(root, 'config/yara-rules');
    const yaraCommunity = countFiles(join(yaraBase, 'community'), '.yar');
    const yaraCustom = countFiles(join(yaraBase, 'custom'), '.yar');
    const yaraAutoGen = countFiles(join(yaraBase, 'auto-generated'), '.yar');
    const yaraTotal = yaraCommunity + yaraCustom + yaraAutoGen;

    const yaraDefinitions =
      countYaraDefinitions(join(yaraBase, 'community')) +
      countYaraDefinitions(join(yaraBase, 'custom')) +
      countYaraDefinitions(join(yaraBase, 'auto-generated'));

    const syncState = readJsonSafe<SyncState>(
      resolve(root, 'packages/threat-cloud/data/threat-intel/sync-state.json'),
    );
    const syncStats = readJsonSafe<SyncStats>(
      resolve(root, 'packages/threat-cloud/data/threat-intel/sync-stats.json'),
    );

    const sources = syncStats?.perSource
      ? syncStats.perSource.filter((s) => s.validated > 0).length
      : 0;
    const validatedRecords = syncStats?.totalRecords ?? 0;

    const meta = readJsonSafe<RulesMeta>(
      resolve(sigmaBase, 'auto-generated/.rules-meta.json'),
    );

    const draftSigma = meta?.sigmaByStatus?.['draft'] ?? 0;
    const draftYara = meta?.yaraByStatus?.['draft'] ?? 0;
    const promotedSigma = meta?.sigmaByStatus?.['promoted'] ?? 0;
    const promotedYara = meta?.yaraByStatus?.['promoted'] ?? 0;

    return NextResponse.json({
      sigma: {
        community: sigmaCommunity,
        custom: sigmaCustom,
        autoGenerated: sigmaAutoGen,
        total: sigmaTotal,
      },
      yara: {
        community: yaraCommunity,
        custom: yaraCustom,
        autoGenerated: yaraAutoGen,
        total: yaraTotal,
        definitions: yaraDefinitions,
      },
      totalRules: sigmaTotal + yaraTotal,
      autoGenerated: {
        sigma: meta?.sigmaRules ?? sigmaAutoGen,
        yara: meta?.yaraRules ?? yaraAutoGen,
        promoted: promotedSigma + promotedYara,
        draft: draftSigma + draftYara,
      },
      lastSync: syncState?.lastSyncAt ?? null,
      sources,
      validatedRecords,
    });
  } catch {
    return NextResponse.json(
      { error: 'Failed to compute rule stats' },
      { status: 500 },
    );
  }
}
