import { NextResponse } from 'next/server';
import { STATS } from '@/lib/stats';

/**
 * GET /api/threat-intel/stats
 *
 * Returns the canonical ATR standard counts (STATS, the single source of truth
 * synced from agent-threat-rules), so every "live" rule-count widget shows the
 * same standard size as the rest of the site. The in-browser scanner runs the
 * production subset (draft/deprecated excluded at bundle-compile time); that
 * subset size is an implementation detail, not the headline number.
 */
export async function GET() {
  try {
    return NextResponse.json({
      atr: {
        total: STATS.atrRules,
        patterns: STATS.atrPatterns,
        promoted: STATS.threatIntel.promotedRules,
        draft: STATS.threatIntel.draftRules,
      },
      autoGenerated: {
        atr: STATS.threatIntel.autoGeneratedATR,
        promoted: STATS.threatIntel.promotedRules,
        draft: STATS.threatIntel.draftRules,
      },
      validatedRecords: STATS.threatIntel.validatedRecords,
      sources: STATS.threatIntel.sources,
      lastSync: STATS.threatIntel.lastSync,
    });
  } catch {
    return NextResponse.json({ error: 'Failed to compute rule stats' }, { status: 500 });
  }
}
