import { NextResponse } from 'next/server';
import { ATR_RULES_COMPILED } from '@/lib/atr-rules-compiled';
import { STATS } from '@/lib/stats';

/**
 * GET /api/threat-intel/stats
 *
 * Returns current rule + threat-intel stats. The rule and pattern counts are
 * computed from the ATR rules actually bundled with this deployment, so the
 * "live" numbers reflect exactly what the in-browser scanner runs (no stale
 * filesystem reads, no zero-fallback). Ecosystem / threat-intel figures come
 * from the verified STATS source of truth.
 */
export async function GET() {
  try {
    const rules = ATR_RULES_COMPILED as ReadonlyArray<{ patterns?: ReadonlyArray<unknown> }>;
    const total = rules.length;
    let patterns = 0;
    for (const r of rules) patterns += Array.isArray(r.patterns) ? r.patterns.length : 0;

    return NextResponse.json({
      atr: {
        total,
        patterns,
        promoted: STATS.threatIntel.promotedRules,
        draft: STATS.threatIntel.draftRules,
      },
      autoGenerated: {
        atr: STATS.threatIntel.autoGeneratedATR,
        promoted: STATS.threatIntel.promotedRules,
        draft: STATS.threatIntel.draftRules,
      },
      validatedRecords: STATS.threatIntel.validatedRecords,
      sources: STATS.threatIntel.sources,
      lastSync: STATS.threatIntel.lastSync,
    });
  } catch {
    return NextResponse.json({ error: 'Failed to compute rule stats' }, { status: 500 });
  }
}
