/**
 * Single source of truth for all marketing statistics.
 *
 * Derived from (verified 2026-03-12):
 *   config/sigma-rules/       -> 3,760 YAML files (3,110 community + 45 custom + 605 auto-generated)
 *   config/yara-rules/        -> 5,961 rule definitions across 969 files (923 community + 3 custom + 43 auto-generated)
 *   packages/panguard-guard/src/types.ts       -> ResponseAction union (11 types)
 *   packages/core/src/ai/funnel-router.ts      -> 3 layers
 *   vitest run (159 test files)                -> 3,490 test cases
 *   packages/panguard/src/cli/index.ts         -> 23 top-level commands
 *   packages/panguard-mcp/src/server.ts        -> 11 MCP tools
 *   packages/panguard-skill-auditor/src/checks/ -> 6 audit checks
 *   agent-threat-rules/rules/                  -> 52 stable ATR rules (+ 17 predicted drafts)
 *   packages/panguard-guard/src/playbook/      -> 3 playbook templates
 *   packages/panguard-guard/src/collectors/     -> 4 log parsers
 *
 * When rules are added/removed, update the numbers here and the entire
 * site picks them up automatically.
 */
export const STATS = {
  /** Must match packages/panguard/package.json "version" */
  cliVersion: '0.3.4',
  sigmaRules: 3_760,
  yaraRules: 5_961,
  atrRules: 52,
  totalRules: 3_760 + 5_961 + 52,
  /** Use this for all user-facing display — avoids stale hardcoded counts */
  totalRulesDisplay: '9,700+' as const,
  /** Separate display for honest breakdown */
  atrRulesDisplay: '52+' as const,
  integratedRulesDisplay: '9,700+' as const,
  falcoConfigs: 1,
  testsPassing: 3_490,
  testFiles: 159,
  detectionLayers: 3,
  responseActions: 11,
  cliCommands: 23,
  products: 3,
  aiAgents: 5,
  mcpTools: 11,
  playbookTemplates: 3,
  logParsers: 4,
  license: 'MIT' as const,
  skillAuditChecks: 6,
  atrDraftRules: 17,
  /** Threat Intel Pipeline stats (auto-updated by CI every hour) */
  threatIntel: {
    sources: 11,
    activeSources: 10,
    validatedRecords: 5_146,
    autoGeneratedSigma: 605,
    autoGeneratedYara: 43,
    promotedRules: 808,
    draftRules: 536,
    lastSync: '2026-03-12',
    syncInterval: '1h',
  },
  lastUpdated: '2026-03-13',
} as const;

export type Stats = typeof STATS;

/** Product maturity label */
export type MaturityLevel = 'GA' | 'Beta' | 'ComingSoon';

/** Maturity status for each feature / product */
export const MATURITY: Record<string, MaturityLevel> = {
  scan: 'GA',
  guard: 'GA',
  chat: 'GA',
  threatCloud: 'GA',
  manager: 'GA',
  skillAuditor: 'Beta',
  mcp: 'Beta',
  trap: 'ComingSoon',
  report: 'ComingSoon',
};
