/**
 * Single source of truth for all marketing statistics.
 *
 * Usage: Import STATS directly in components. RuleStatsContext wraps STATS
 * with live API data from /api/threat-intel/stats (rule counts only).
 * Ecosystem stats are static until P2 TC API integration.
 *
 * When adding new stats: update here first, then all components auto-update.
 *
 * Derived from (verified 2026-03-12):
 *   packages/panguard-guard/src/types.ts       -> ResponseAction union (11 types)
 *   packages/core/src/ai/funnel-router.ts      -> 3 layers
 *   vitest run (159 test files)                -> 3,528 test cases
 *   packages/panguard/src/cli/index.ts         -> 23 top-level commands
 *   packages/panguard-mcp/src/server.ts        -> 11 MCP tools
 *   packages/panguard-skill-auditor/src/checks/ -> 8 audit checks
 *   agent-threat-rules/rules/                  -> 71 ATR rules
 *   packages/panguard-guard/src/playbook/      -> 3 playbook templates
 *   packages/panguard-guard/src/collectors/     -> 4 log parsers
 *
 * When rules are added/removed, update the numbers here and the entire
 * site picks them up automatically.
 */
export const STATS = {
  /** Must match packages/panguard/package.json "version" */
  cliVersion: '1.4.2',
  atrRules: 71,
  /** Community ATR rules from Threat Cloud flywheel */
  atrCommunityRules: 0,
  /** Total unique detection patterns across all ATR rules (compiled from YAML) */
  atrPatterns: 520,
  totalRules: 71,
  /** Use this for all user-facing display — avoids stale hardcoded counts */
  totalRulesDisplay: '71' as const,
  /** Separate display for honest breakdown */
  atrRulesDisplay: '71' as const,
  /** Promotion interval in Threat Cloud */
  promotionIntervalMinutes: 2,
  testsPassing: 3_528,
  testFiles: 159,
  detectionLayers: 3,
  responseActions: 11,
  cliCommands: 23,
  products: 6,
  aiAgents: 4,
  mcpTools: 11,
  playbookTemplates: 3,
  logParsers: 4,
  license: 'MIT' as const,
  skillAuditChecks: 8,
  atrDraftRules: 17,
  /**
   * OWASP Agentic Top 10 coverage (from agent-threat-rules/docs/OWASP-MAPPING.md)
   * Sync when rules are added/removed.
   */
  owaspAgentic: {
    totalCategories: 10,
    coveredCategories: 10,
    totalMappings: 77,
    categories: [
      { id: 'ASI01', rules: 13, strength: 'STRONG' as const },
      { id: 'ASI02', rules: 11, strength: 'STRONG' as const },
      { id: 'ASI03', rules: 9, strength: 'STRONG' as const },
      { id: 'ASI04', rules: 8, strength: 'STRONG' as const },
      { id: 'ASI05', rules: 8, strength: 'STRONG' as const },
      { id: 'ASI06', rules: 8, strength: 'STRONG' as const },
      { id: 'ASI07', rules: 5, strength: 'MODERATE' as const },
      { id: 'ASI08', rules: 4, strength: 'MODERATE' as const },
      { id: 'ASI09', rules: 5, strength: 'MODERATE' as const },
      { id: 'ASI10', rules: 7, strength: 'MODERATE' as const },
    ],
  },
  /** Threat Intel Pipeline stats (auto-updated by CI every hour) */
  threatIntel: {
    sources: 11,
    activeSources: 10,
    validatedRecords: 5_146,
    autoGeneratedATR: 0,
    promotedRules: 808,
    draftRules: 536,
    lastSync: '2026-03-12',
    syncInterval: '1h',
  },
  /**
   * Ecosystem scanning stats (from crawl-mcp-registry + audit-npm-skills-v2 pipeline)
   *
   * Pipeline: crawl-mcp-registry.ts → audit-npm-skills-v2.ts → push-to-threat-cloud.ts
   * Source: npm registry, GitHub API, awesome-lists (8 queries, pagination)
   * Updated: 2026-03-16
   */
  ecosystem: {
    /** Total MCP/AI skill entries crawled from registries */
    entriesCrawled: 36_394,
    /** npm packages found in crawl */
    npmPackages: 2_769,
    /** Packages actually scanned by ATR + Skill Auditor (L1 + L2 AST) */
    skillsScanned: 10_000,
    /** Total MCP tool definitions extracted from scanned packages */
    toolsExtracted: 35_858,
    /** Packages with security findings (any severity) */
    packagesWithFindings: 1_228,
    /** Threats detected (confirmed + suspicious) — legacy alias */
    maliciousFound: 1_228,
    /** ATR rule candidates from scan findings */
    atrRulesGenerated: 225,
    /** Total ATR rule matches across all packages */
    atrRuleMatches: 3_361,
    /** Top ATR rule: ATR-2026-099 hit count */
    topAtrRuleHits: 1_515,
    /** Triple threat packages (shell + network + filesystem access) */
    tripleThreat: 249,
    /** Packages with postinstall scripts */
    postinstallScripts: 122,
    /** Breakdown by severity */
    findingsCritical: 97,
    findingsHigh: 532,
    findingsMedium: 324,
    findingsLow: 291,
    findingsClean: 1_352,
    registrySources: 3,
    lastCrawl: '2026-03-18',
  },
  /**
   * NOTE: These fallback numbers are only used when TC live API is unreachable.
   * Website components should always prefer fetchLiveMetrics() for real-time data.
   * Update these periodically to keep fallbacks reasonable.
   */
  lastUpdated: '2026-03-26',
} as const;

export type Stats = typeof STATS;

/**
 * Live metrics from Threat Cloud API.
 * Used on the website to show real-time numbers from all scan sources.
 * Falls back to static STATS.ecosystem values if TC is unavailable.
 *
 * Usage:
 *   const metrics = await fetchLiveMetrics();
 *   // metrics.totalSkillsScanned -- from all sources (bulk + CLI + web)
 *   // metrics.totalAgentsProtected -- unique devices with panguard installed
 */
export interface LiveMetrics {
  totalSkillsScanned: number;
  totalAgentsProtected: number;
  totalThreatsDetected: number;
  totalAtrRules: number;
  sources: {
    bulk: { skills: number; findings: number };
    cli: { skills: number; findings: number; devices: number };
    web: { skills: number; findings: number };
  };
  lastUpdated: string;
}

const TC_METRICS_URL = process.env['THREAT_CLOUD_URL']
  ? `${process.env['THREAT_CLOUD_URL']}/api/metrics`
  : 'https://tc.panguard.ai/api/metrics';

/** Fetch live metrics from Threat Cloud, with static fallback */
export async function fetchLiveMetrics(): Promise<LiveMetrics> {
  try {
    const resp = await fetch(TC_METRICS_URL, {
      next: { revalidate: 60 },
    } as RequestInit);
    if (!resp.ok) throw new Error(`TC returned ${resp.status}`);
    const json = (await resp.json()) as { ok: boolean; data: LiveMetrics };
    if (json.ok && json.data) return json.data;
  } catch {
    // Fallback to static stats
  }

  return {
    totalSkillsScanned: STATS.ecosystem.skillsScanned,
    totalAgentsProtected: 0,
    totalThreatsDetected: STATS.ecosystem.maliciousFound,
    totalAtrRules: STATS.atrRules,
    sources: {
      bulk: { skills: STATS.ecosystem.skillsScanned, findings: STATS.ecosystem.maliciousFound },
      cli: { skills: 0, findings: 0, devices: 0 },
      web: { skills: 0, findings: 0 },
    },
    lastUpdated: STATS.lastUpdated,
  };
}

/** Product maturity label */
export type MaturityLevel = 'GA' | 'Beta' | 'ComingSoon';

/** Maturity status for each feature / product */
export const MATURITY: Record<string, MaturityLevel> = {
  scan: 'GA',
  guard: 'GA',
  chat: 'GA',
  threatCloud: 'GA',
  skillAuditor: 'GA',
  mcp: 'Beta',
  trap: 'Beta',
  report: 'GA',
};
